### ISSUE TITLE
Incorrect collectionName on test3.js

### ISSUE THREAD

**Issue by fairstyle** [videsk/backend-jr-hiring#1]
[test3.test.js](https://github.com/videsk/backend-jr-hiring/blob/main/test/test3.test.js) file has incorrect collectionName
line 46 `const { id } = db.users[2]; `  **->**  `const { id } = db.orgs[2];`

![ERROR](https://user-images.githubusercontent.com/9719533/144547731-36942faf-3f26-4521-b28b-25d8f4c65680.png)

![CORREGIDO](https://user-images.githubusercontent.com/9719533/144547733-1c6eeda7-ba9c-451b-9eb2-6959668096d5.png)

**Comment by matiaslopezd** [comment]
Hi @fairstyle! Thank you for notifying us! 👏🏻
